version: '3.8'

services:
  app:
    container_name: k6-dashboard
    image: rfieq/k6-pro-dashboard:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    volumes:
      - ./results:/app/results
    working_dir: /app
    restart: unless-stopped
    # Environment variables overrides (Optional)
    # environment:
    #   - TARGET_URL=https://test-api.k6.io
